{
  "____comment": "This file was generated by eosio-abigen. DO NOT EDIT - 2018-09-10T19:11:04",
  "version": "eosio::abi/1.0",
  "types": [],
  "structs": [{
      "name": "init",
      "base": "",
      "fields": []
    }
  ],
  "actions": [{
      "name": "init",
      "type": "init",
      "ricardian_contract": ""
    }
  ],
  "tables": [],
  "ricardian_clauses": [],
  "error_messages": [],
  "abi_extensions": []
}